# Generated by Django 4.1.3 on 2022-11-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
